Admin/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, jsonify, session, make_response
from flask_redis import FlaskRedis
from flask_caching import Cache, CachedResponse
from flask_login import login_required, fresh_login_required
from Models.base_model import db, get_local_time
from Models.users import Role
from Models.users import Patients, PatientAddress, Staff
from Models.medicine import Medicine, Inventory, InventoryHistory
from Models.diseases import Disease
from Models.payment import Payment
from Models.lab_analysis import LabAnalysis, LabAnalysisDetails
from Models.appointment import Appointment, Feedback
from Models.prescription import Prescription, PrescriptionDetails
from Models.diagnosis import Diagnosis, DiagnosisDetails
from Models.clinic import Clinic, ClinicType
from .form import AddPatientForm, DiagnosisForm, PrescriptionForm, LabAnalysisForm, AddDiseaseForm, AddMedicineForm, FeedbackForm, AddClinicForm, UpdatedPasswordForm
from Utils.notification_service import NotificationService
from Auth.form import StaffRegistrationForm
from Utils.export_pdf import generate_payment_pdf
from Utils.export_appointment import generate_appointment_pdf
from decorator import role_required, branch_required
from collections import defaultdict
from sqlalchemy.sql import func, desc
from slugify import slugify

admin = Blueprint("admin", __name__)
cache = Cache()
redis_client = FlaskRedis()
region_districts = {
  "Arusha": ["Monduli", "Arusha", "Arumeru", "Karatu", "Longido", "Ngorongoro"],
  "Dar es Salaam": ["Ilala", "Kinondoni", "Temeke", "Kigamboni", "Ubungo"],
  "Dodoma": ["Bahi", "Chamwino", "Chemba", "Dodoma", "Kondoa", "Kongwa", "Mpwapwa"],
  "Geita": ["Bukombe", "Chato", "Geita", "Mbogwe", "Nyang'hwale"],
  "Iringa": ["Iringa", "Kilolo", "Mafinga Town", "Mufindi"],
  "Kagera": ["Biharamulo", "Bukoba", "Karagwe", "Kyerwa", "Missenyi", "Muleba", "Ngara"],
  "Katavi": ["Mlele", "Mpanda"],
  "Kigoma": ["Buhigwe", "Kakonko", "Kasulu", "Kibondo", "Kigoma", "Uvinz"],
  "Kilimanjaro": ["Hai", "Moshi", "Mwanga", "Rombo", "Same", "Siha"],
  "Lindi": ["Kilwa", "Lindi", "Liwale", "Nachingwea", "Ruangwa"],
  "Manyara": ["Babati", "Hanang", "Kiteto", "Mbulu", "Simanjiro"],
  "Mara": ["Bunda", "Butiama", "Musoma", "Rorya", "Serengeti", "Tarime"],
  "Mbeya": ["Busokelo", "Chunya", "Kyela", "Mbarali", "Mbeya", "Rungwe"],
  "Mororgoro": ["Gairo", "Kilombero", "Kilosa", "Morogoro", "Mvomero", "Ulanga"],
  "Mtwara": ["Masasi", "Mtwara", "Nanyumbu", "Newala", "Tandahimba"],
  "Mwanza": ["Ilemela", "Kwimba", "Magu", "Misungwi", "Nyamagana", "Sengerema", "Ukerewe"],
  "Njombe": ["Ludewa", "Makambako Town", "Makete", "Njombe", "Wanging'ombe"],
  "Pwani": ["Bagamoyo", "Kibaha", "Kisarawe", "Mafia", "Mkuranga", "Rufiji"],
  "Rukwa": ["Kalambo", "Nkasi", "Sumbawanga"],
  "Ruvuma": ["Mbinga", "Namtumbo", "Nyasa", "Songea", "Tunduru"],
  "Shinyanga": ["Kahama", "Kishapu", "Shinyanga"],
  "Simiyu": ["Bariadi", "Busega", "Itilima", "Maswa", "Meat"],
  "Singida": ["Ikungi", "Iramba", "Manyoni", "Mkalama", "Singida"],
  "Songwe": ["Ileje", "Mbozi", "Momba", "Songwe"],
  "Tabora": ["Igunga", "Kaliua", "Nzega", "Sikonge", "Tabora", "Uyu"],
  "Tanga": ["Handeni", "Kilindi", "Korogwe", "Lushoto", "Mkinga", "Muheza", "Pangani", "Tanga"],
  "Zanzibar": ["Zanzibar Central/South", "Zanzibar North", "Zanzibar Urban/West"]
}

@admin.route("/")
@admin.route("/home")
@admin.route("/branches")
@login_required
@fresh_login_required
@role_required(["SuperAdmin", "Admin"])
def clinic_branches():
  form = AddClinicForm()

  form.owner_id.choices = [(staff.id, f"{staff.first_name} {staff.last_name}") for staff in Staff.query.filter_by(role_id=Role.query.filter_by(name="Admin").first().id).all()]
  form.owner_id.choices.insert(0, ("", "-- Select an admin --"))
  
  context = {
    "form": form,
    "clinics": Clinic.query.all()
  }

  return CachedResponse(
    response = make_response(render_template("Main/select-branch.html", **context)),
    timeout=600
  )

@admin.route("/select-branch", methods=["POST"])
@login_required
@fresh_login_required
@role_required(["SuperAdmin", "Admin"])
def add_branch():
  form = AddClinicForm()
  form.owner_id.choices = [(staff.id, f"{staff.first_name} {staff.last_name}") for staff in Staff.query.filter_by(role_id=Role.query.filter_by(name="Admin").first().id).all()]
  form.owner_id.choices.insert(0, ("", "-- Select an admin --"))

  if form.validate_on_submit():
    cache.clear()
    try:
      new_clinic = Clinic(
        name = form.name.data,
        alias = slugify(form.name.data),
        region = form.region.data,
        district = form.district.data,
        clinic_type_id = ClinicType.query.filter_by(id=form.clinic_type_id.data).first().id,
        owner_id = form.owner_id.data if form.owner_id.data else None,
        date_created = get_local_time()
      )
      db.session.add(new_clinic)
      db.session.commit()
      populate_inventory(new_clinic.unique_id)
      flash("Branch added successfully", "success")
      return redirect(url_for("admin.clinic_branches"))
    except Exception as e:
      flash(f"{str(e)}", "danger")
      return redirect(url_for("admin.clinic_branches"))

  if form.errors != {}:
    for err_msg in form.errors.values():
      flash(f"{err_msg}", "danger")

  return redirect(url_for("admin.clinic_branches"))

def populate_inventory(branch_id):
  try:
    clinic = Clinic.query.filter_by(unique_id=branch_id).first()
    medicines = Medicine.query.all()
    clinic_inventory = Inventory.query.filter_by(clinic_id=clinic.id).all()
    if len(medicines) != len(clinic_inventory):
      for medicine in medicines:
        existing_clinic_inventory = Inventory.query.filter_by(clinic_id=clinic.id, medicine_id=medicine.id).first()
        if not existing_clinic_inventory:
          new_inventory = Inventory(
            clinic_id = clinic.id,
            medicine_id = medicine.id,
            quantity = 0
          )
          db.session.add(new_inventory)
          db.session.commit()

          # record_opening_stock(new_inventory.id, new_inventory.quantity, "Opening Stock", new_inventory.quantity)

  except Exception as e:
    db.session.rollback()
    print(f"{str(e)}")

@admin.route("/edit-branch/<string:branch_name>", methods=["POST", "GET"])
@login_required
@fresh_login_required
@role_required(["SuperAdmin", "Admin"])
def edit_branch(branch_name):
  branch = Clinic.query.filter_by(alias=branch_name).first()
  if not branch:
    flash("Clinic branch not found", "danger")
    return redirect(url_for('admin.clinic_branches'))

  form = AddClinicForm(obj=branch)
  
  form.owner_id.choices = [(staff.id, f"{staff.first_name} {staff.last_name}") for staff in Staff.query.filter_by(role_id=Role.query.filter_by(name="Admin").first().id).all()]
  form.owner_id.choices.insert(0, ("", "-- Select an admin --"))

  if form.validate_on_submit():
    cache.clear()
    try:
      form.populate_obj(obj=branch)
      if not form.owner_id.data:
        branch.owner_id = None
      db.session.commit()
      flash("Branch updated successfully", "success")
      return redirect(url_for("admin.clinic_branches"))
    except Exception as e:
      flash(f"{str(e)}", "danger")
      return redirect(url_for("admin.clinic_branches"))

  if form.errors != {}:
    for err_msg in form.errors.values():
      flash(f"{err_msg}", "danger")

  context = {
    "form": form
  }

  return render_template("Main/edit-branch.html", **context)

@admin.route("/load/branch/<string:branch_name>")
@login_required
@fresh_login_required
@role_required(["SuperAdmin", "Admin"])
def load_clinic(branch_name):
  cache.clear()
  try:
    clinic = Clinic.query.filter_by(alias=branch_name).first()
    if not clinic:
      flash("Branch not found", "danger")
      return redirect(url_for('admin.clinic_branches'))  
    if not clinic.is_active:
      flash("Branch is closed, cannot navigate to it", "info")
      return redirect(url_for('admin.clinic_branches'))  
    session["clinic_id"] = clinic.id
    return redirect(url_for('admin.dashboard'))
  except Exception as e:
    flash(f"{str(e)}", "danger")
    return redirect(url_for('admin.clinic_branches'))

@admin.route("/close-branch/<string:branch_name>")
@login_required
@fresh_login_required
@role_required(["SuperAdmin", "Admin"])
def close_clinic(branch_name):
  cache.clear()
  try:
    clinic = Clinic.query.filter_by(alias=branch_name).first()
    if not clinic:
      flash("Branch not found", "danger")
    else:
      clinic_count = Clinic.query.count()
      if clinic_count != 1:
        clinic.is_active = False
        db.session.commit()
        flash(f"Branch {clinic.name} closed successfully", "success")
      else:
        flash("You need to have at least one branch registered", "warning")
      session.pop("clinic_id", None)
    return redirect(url_for('admin.clinic_branches'))
  except Exception as e:
    flash(f"{str(e)}", "danger")
    return redirect(url_for('admin.clinic_branches'))

@admin.route("/reopen-branch/<string:branch_name>")
@login_required
@fresh_login_required
@role_required(["SuperAdmin", "Admin"])
def reopen_clinic(branch_name):
  cache.clear()
  try:
    clinic = Clinic.query.filter_by(alias=branch_name).first()
    if not clinic:
      flash("Branch not found", "danger")
    elif clinic.is_active:
      flash("Cannot reopen an already open clinic", "info")
    else:
      clinic.is_active = True
      db.session.commit()
      flash(f"Branch {clinic.name} has been reopend successfully", "success")
    return redirect(url_for('admin.clinic_branches'))
  except Exception as e:
    flash(f"{str(e)}", "danger")
    return redirect(url_for('admin.clinic_branches'))

@admin.route("/dashboard")
@login_required
@fresh_login_required
@branch_required()
def dashboard():
  form = StaffRegistrationForm()
  form.branch.choices = [(clinic.unique_id, clinic.name) for clinic in Clinic.query.all()]

templates/Main/add-disease.html
{% extends "base.html" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/patient.css')}}">
{% endblock %}

{% block title %}
{% if not title_message %}
Add Disease
{% else %}
Edit Disease
{% endif %}
{% endblock %}

{% block nav %}
<a href="{{ url_for('admin.dashboard') }}" class="nav-item">
  <i class="fas fa-chevron-left"></i>
  Back To Dashboard
</a>
{% endblock %}

{% block body %}
<div class="container">
  <div class="header">
    <div class="page-title">
      {% if not title_message %}
      <h1>New Disease</h1>
      {% else %}
      <h1>Edit Disease Details</h1>
      {% endif %}
    </div>
  </div>

  <div class="patient-form-container">
    <form method="POST">
      {{ form.csrf_token() }}

      <div class="form-section">
        <div class="form-grid">
          <div class="form-group extend">
            {{ form.name.label }}
            {{ form.name(class="form-control", placeholder="Enter name of disease") }}
            {% if form.name.errors %}
            <div class="error-message">{{ form.name.errors[0] }}</div>
            {% endif %}
          </div>
        </div>
      </div>

      <div class="form-actions">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/Main/add-medicine.html
{% extends "base.html" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/patient.css')}}">
{% endblock %}

{% block title %}
{% if not title_message %}
Add Medicine
{% else %}
Edit Medicine
{% endif %}
{% endblock %}

{% block nav %}
<a href="{{ url_for('admin.dashboard') }}" class="nav-item">
  <i class="fas fa-chevron-left"></i>
  Dashboard
</a>
{% endblock %}

{% block body %}
<div class="container">
  <div class="header">
    <div class="page-title">
      {% if not title_message %}
      <h1>New Medicine</h1>
      {% else %}
      <h1>Edit Medicine Details</h1>
      {% endif %}
    </div>
  </div>
  <div class="patient-form-container">
    <form method="post">
      {{ form.csrf_token() }}
      <div class="form-section">
        <div class="form-grid">
          <div class="form-group">
            {{ form.name.label }}
            {{ form.name(class="form-control", placeholder="Enter name of medicine") }}
            {% if form.name.errors %}
            <div class="error-message">{{ form.name.errors[0] }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.price.label }}
            {{ form.price(class="form-control", placeholder="Enter price of medicine in (Tsh)") }}
            {% if form.price.errors %}
            <div class="error-message">{{ form.price.errors[0] }}</div>
            {% endif %}
          </div>
          <div class="form-group extend">
            {{ form.quantity.label }}
            {{ form.quantity(class="form-control", value="", placeholder="Enter quantity to add") }}
            {% if form.quantity.errors %}
            <div class="error-message">{{ form.quantity.errors[0] }}</div>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="form-actions">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/Main/add-patient.html
{% extends "base.html" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/patient.css')}}">
{% endblock %}

{% block title %}
{% if not title_message %}
Add Patient
{% else %}
Edit Patient
{% endif %}
{% endblock %}

{% block nav %}
<a href="{{ url_for('admin.dashboard') }}" class="nav-item">
  <i class="fas fa-chevron-left"></i>
  Back To Dashboard
</a>
{% if title_message %}
<a href="{{ url_for('admin.patient_profile', patient_id=patient.unique_id) }}" class="nav-item">
  <i class="fas fa-user-injured"></i> Client Profile
</a>
{% endif %}
{% endblock %}

{% block body %}
<div class="container">
  <div class="header">
    <div class="page-title">
      {% if not title_message %}
      <h1>New Patient Registration</h1>
      {% else %}
      <h1>Edit Patient Details</h1>
      {% endif %}
    </div>
  </div>

  <div class="patient-form-container">
    <form method="POST">
      {{ form.hidden_tag() }}

      <div class="form-section">
        <h2 class="section-title">Personal Information</h2>
        <div class="form-grid">
          <div class="form-group">
            {{ form.first_name.label }}
            {{ form.first_name(class="form-control", placeholder="Enter First Name") }}
            {% if form.first_name.errors %}
            <div class="error-message">{{ form.first_name.errors[0] }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.last_name.label }}
            {{ form.last_name(class="form-control", placeholder="Enter Last Name") }}
            {% if form.last_name.errors %}
            <div class="error-message">{{ form.last_name.errors[0] }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.age.label }}
            {{ form.age(class="form-control", placeholder="Enter Patient's Age") }}
            {% if form.age.errors %}
            <div class="error-message">{{ form.age.errors[0] }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.gender.label }}
            {{ form.gender(class="form-control") }}
            {% if form.gender.errors %}
            <div class="error-message">{{ form.gender.errors[0] }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.phone_number_1.label }}
            {{ form.phone_number_1(class="form-control", placeholder="Enter Primary Phone Number") }}
            {% if form.phone_number_1.errors %}
            <div class="error-message">{{ form.phone_number_1.errors[0] }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.phone_number_2.label }}
            {{ form.phone_number_2(class="form-control", placeholder="Enter Secondary Phone Number") }}
            {% if form.phone_number_2.errors %}
            <div class="error-message">{{ form.phone_number_2.errors[0] }}</div>
            {% endif %}
          </div>
        </div>
      </div>

      <div class="form-section">
        <h2 class="section-title">Address Information</h2>
        {% if patient and patient.address_id %}
        <div class="patient-address-box">
          <h4>Saved Address</h4>
          {{ patient.patient_address.region }}, {{ patient.patient_address.district }}, {{
          patient.patient_address.location }}
        </div>
        {% endif %}
        <div class="form-grid">
          <div class="form-group">
            {{ form.region.label }}
            {{ form.region(class="form-control", id="region", onclick="loadDistricts()") }}
            {% if form.region.errors %}
            <div class="error-message">{{ form.region.errors[0] }}</div>
            {% endif %}
          </div>
          <div class="form-group">
            {{ form.district.label }}
            {{ form.district(class="form-control", id="district") }}
            {% if form.district.errors %}
            <div class="error-message">{{ form.district.errors[0] }}</div>
            {% endif %}
          </div>
          <div class="form-group extend">
            {{ form.location.label }}
            {{ form.location(class="form-control", placeholder="Enter Specific Location") }}
            {% if form.location.errors %}
            <div class="error-message">{{ form.location.errors[0] }}</div>
            {% endif %}
          </div>
        </div>
      </div>

      <div class="form-actions">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='js/location.js') }}"></script>
{% endblock %}

templates/Main/disease.html
{% extends "base.html" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/disease.css')}}">
{% endblock %}

{% block title %} 
disease page 
{% endblock %}

{% block body %}
<div class="header">
<a href ="{{url_for('New_disease')}}">
    <button>Add Disease</button>
</a>
<input id="record_search" placeholder="Search for Disease" />
</div>

<table class="table">
    <tr>
        <th>id</th>
        <th>Name</th>
        <th>Action</th>
    </tr>
    {% for disease in diseases %}
        <tr class="record">
            <td>{{disease.id}}</td>
            <td>{{disease.name}}</td>
            <td id="action">
                <a href="{{ url_for('remove_disease', disease_id=disease.id) }}">Remove</a>
                <a href="{{ url_for('edit_disease',disease_id=disease.id) }}">Edit</a>
            </td>
        </tr>
    {% endfor %}
</table>
<script src="{{ url_for('static', filename='js/client.js') }}"></script>
{% endblock %}

templates/Main/edit-branch.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/select-branch.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/edit-branch.css') }}">
{% endblock %}

{% block title %}
Select Branch
{% endblock %}

{% block body %}
<div class="container">
  <div class="container-header">
    <h1>Edit Clinic</h1>
  </div>
  <form id="editClinicForm" method="post">
    {{ form.csrf_token }}
    <div class="form-group extend">
      {{ form.name.label }}
      {{ form.name(placeholder="Enter Clinic Name") }}
    </div>
    <div class="form-group">
      {{ form.region.label }}
      {{ form.region(placeholder="Enter name of region") }}
    </div>
    <div class="form-group">
      {{ form.district.label }}
      {{ form.district(placeholder="Enter name of district") }}
    </div>
    <div class="form-group extend">
      {{ form.clinic_type_id.label }}
      {{ form.clinic_type_id }}
    </div>
    <div class="form-group extend">
      {{ form.owner_id.label }}
      {{ form.owner_id }}
    </div>
  </form>

  <div class="form-actions">
    <a href="{{ url_for('admin.clinic_branches') }}">
      <button class="btn-primary" id="cancelBtn">Back</button>
    </a>
    <button form="editClinicForm" type="submit" class="btn-primary">Update Branch</button>
  </div>
</div>

{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='js/select_branch.js') }}"></script>
{% endblock %}

templates/Main/select-branch.html
{% extends 'base.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/select-branch.css') }}">
{% endblock %}

{% block title %}
Select Branch
{% endblock %}

{% block body %}
<div class="container">
  <div class="branches-box">
    <div class="branch-header">
      <h2>
        Clinic Branches
        <span>{{ clinics|count }}</span>
      </h2>
      <button id="addBranchBtn" class="btn-primary">+ Add New Branch</button>
    </div>
    <div class="branches-list">
      {% if clinics %}
      {% for clinic in clinics %}
      <div class="branch">
        <div class="branch-box">
          <p class="branch-name">
            {{ clinic.name }} {% if clinic.clinic_type.name == "Headquarters" %} - HQ {% endif %}
          </p>
          <p class="branch-address">
            {{ clinic.region }}, {{ clinic.district }}
          </p>
          {% if clinic.is_active %}
          <span class="status-badge completed">Open</span>
          {% else %}
          <span class="status-badge cancelled">Closed</span>
          {% endif %}
        </div>
        <div class="branch-stats-box">
          <div class="branch-stat">
            <i></i>
            <p>
              <span>{{ clinic.patients|count }}</span>
              <b>
                Patient{% if clinic.patients|count != 1 %}s{% endif %}
              </b>
            </p>
          </div>
          <div class="branch-stat">
            <i></i>
            <p>
              <span>{{ clinic.staff|count }}</span>
              <b>Staff{% if clinic.staff|count != 1 %}s{% endif %}</b>
            </p>
          </div>
          <div class="branch-stat">
            <i></i>
            <p>
              <span>{{ clinic.prescription|count }}</span>
              <b>Prescription{% if clinic.prescription|count != 1 %}s{% endif %}</b>
            </p>
          </div>
          <div class="branch-stat">
            <i></i>
            <p>
              <span>{{ clinic.diagnosis|count }}</span>
              <b>Diagnos{% if clinic.diagnosis|count != 1 %}es{% else %}is{% endif %}</b>
            </p>
          </div>
          <div class="branch-stat">
            <i></i>
            <p>
              <span>{{ clinic.inventory|count }}</span>
              <b>Medicine{% if clinic.inventory|count != 1 %}s{% endif %}</b>
            </p>
          </div>
        </div>
        <div class="branch-action">
          {% if clinic.is_active %}
          <a id="navigate-link" href="{{ url_for('admin.load_clinic', branch_name=clinic.alias) }}">
            <button>
              Navigate
              <i class="fas fa-arrow-right"></i>
            </button>
          </a>
          <a id="remove-link" href="{{ url_for('admin.close_clinic', branch_name=clinic.alias) }}">
            <button>
              Close
              <i class="fas fa-lock"></i>
            </button>
          </a>
          <a id="edit-link" href="{{ url_for('admin.edit_branch', branch_name=clinic.alias) }}">
            <button>
              Edit
              <i class="fas fa-edit"></i>
            </button>
          </a>
          {% else %}
          <a id="open-link" href="{{ url_for('admin.reopen_clinic', branch_name=clinic.alias) }}">
            <button>
              Reopen
              <i class="fas fa-key"></i>
            </button>
          </a>
          {% endif %}
        </div>
      </div>
      {% endfor %}
      {% else %}
      <p class="else">No branches added</p>
      {% endif %}
    </div>
  </div>
</div>

<div id="branchModal" class="modal active">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Add New Clinic Branch</h2>
    <form action="{{ url_for('admin.add_branch') }}" id="branchForm" method="post">
      {{ form.csrf_token }}
      <div class="form-group extend">
        {{ form.name.label }}
        {{ form.name(placeholder="Enter Clinic Name") }}
      </div>
      <div class="form-group">
        {{ form.region.label }}
        {{ form.region(placeholder="Enter name of region") }}
      </div>
      <div class="form-group">
        {{ form.district.label }}
        {{ form.district(placeholder="Enter name of district") }}
      </div>
      <div class="form-group extend">
        {{ form.clinic_type_id.label }}
        {{ form.clinic_type_id }}
      </div>
      <div class="form-group extend">
        {{ form.owner_id.label }}
        {{ form.owner_id }}
      </div>

      <div class="form-actions">
        <button type="button" class="btn-primary" id="cancelBtn">Cancel</button>
        <button type="submit" class="btn-primary">Add Branch</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='js/select_branch.js') }}"></script>
{% endblock %}